import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles1/Home.module.css";
import { Col, DatePicker, Form, Input, Radio, Row, Select } from "antd";
import { useDispatch, useSelector } from "react-redux";
import { useState, useEffect } from "react";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to The <a href="https://nextjs.org">Jungle!</a>
        </h1> */}

        <p className={styles.description}>
          Date Picker Example
        </p>

        <div className={styles.grid}>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Date Picker 1"
						name="date_example_1"
					>
          <DatePicker
                  //   disabled={!closeApp}
                  placeholder="Sample Date Picker"
                  //   disabledDate={disabledStartDate}
                  //   onChange={onStartChange}
                  //   value={startValue}
                  showToday={false}
                  format={'DD-MMM-YYYY'}
                />					
          </Form.Item>
				</Col>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Date Picker 2"
						name="date_example_2"
					>
					<DatePicker
                  //   disabled={!closeApp}
                  placeholder="Sample Date Picker"
                  //   disabledDate={disabledStartDate}
                  //   onChange={onStartChange}
                  //   value={startValue}
                  showToday={false}
                  format={'DD-MM-YYYY'}
                />	
					</Form.Item>
				</Col>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Date Picker 3"
						name="date_example_3"
					>
          <DatePicker
                  // disabled
                  placeholder="Sample Date Picker"
                  //   disabledDate={disabledStartDate}
                  //   onChange={onStartChange}
                  //   value={startValue}
                  showToday={false}
          />	
					</Form.Item>
				</Col>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Date Picker 4"
						name="date_example_4"
					>
          <DatePicker
                  disabled
                  placeholder="Sample Date Picker"
                  //   disabledDate={disabledStartDate}
                  //   onChange={onStartChange}
                  //   value={startValue}
                  showToday={false}
          />	
					</Form.Item>
				</Col>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}