import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles1/Home.module.css";
import { Col, DatePicker, Form, Input, Radio, Row, Select } from "antd";
import ApplicationStorage from "src/utils/application-storage";
import { useDispatch, useSelector } from "react-redux";

export default function Home(props) {

  const { TextArea } = Input;

  const data = useSelector((state) => state.data);
  ApplicationStorage.value = data
  const category = data?.products?.category
  const brand = data?.products?.brand
  const price = data?.products?.price
  const rating = data?.products?.rating

  // console.log('data?', data
  // console.log('kalo ini apa', data?.products?.brand)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to The <a href="https://nextjs.org">Jungle!</a>
        </h1> */}

        <p className={styles.description}>
          Input Text Example
        </p>

        <div className={styles.grid}>
          <Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Input Text 1"
						name="category"
					>
						<Input
            defaultValue={category}/>
					</Form.Item>
				</Col>
          <Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Input Text 2"
						name="brand"
					>
					<Input
          defaultValue={brand}
          />
					</Form.Item>
				  </Col>
          <Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Input Text 3"
						name="price"
					>
					<Input
          defaultValue={price}
          readOnly
          />
					</Form.Item>
				  </Col>
          <Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Input Text 4"
						name="rating"
					>
					<Input
          defaultValue={rating}
          disabled
          />
					</Form.Item>
				  </Col>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}