import Head from "next/head";
import { Row, Col, Form, Button, Checkbox as CheckControlled } from "antd";
import styles from './style.module.less';
import Checkbox from "src/components/Checkbox";
import { useState } from "react";


export default function Home() {
  const [normalCheckbox, setNormalCheckbox] = useState("")
  const [disableCheckbox, setDisableCheckbox] = useState("")
  const [checked, setChecked] = useState(true);
  const [disabled, setDisabled] = useState(false);


  const normalValueCheckbox = (e) => {
    setNormalCheckbox(e)
  }


  const disableValueCheckbox = (e) => {
    setDisableCheckbox(e)
  }


  const toggleChecked = () => {
    setChecked(prevChecked => !prevChecked);
  };


  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <p className={styles.description}>
          Checkbox Example
        </p>


        <div className={styles.grid}>
          <Col md={30} xs={30}>
            <h1 style={{ fontSize: "16px", marginBottom: "10px", fontWeight: "bold" }}>Normal Checkbox</h1>
            <Checkbox onChange={normalValueCheckbox} />
            <p className={styles.selected}>You selected: {normalCheckbox}</p>
          </Col>


          <hr />


          <Col md={30} xs={30} style={{ marginTop: "15px"}}>
            <h1 style={{ fontSize: "16px", marginBottom: "10px", fontWeight: "bold" }}>Disable Checkbox</h1>
            <Checkbox onChange={disableValueCheckbox} isDisable={true} />
            <p className={styles.selected}>You selected: {disableCheckbox}</p>
          </Col>


          <hr />


          <Col md={30} xs={30} style={{ marginTop: "15px"}}>
            <h1 style={{ fontSize: "16px", marginBottom: "10px", fontWeight: "bold" }}>Controlled Checkbox</h1>
              <CheckControlled value="controlled" checked={checked} disabled={disabled} className={styles.checkBox}>Control this checkbox with button below</CheckControlled>


              <Row style={{ marginTop: "20px", marginBottom: "20px" }}>
                <Col style={{ marginRight: "10px" }}>
                  <Button type="primary" onClick={toggleChecked}>
                    {!checked ? 'Check' : 'Uncheck'}
                  </Button>
                </Col>
                <Col>
                  <Button type="primary" onClick={toggleDisabled}>
                    {!disabled ? 'Disable' : 'Enable'}
                  </Button>
                </Col>
              </Row>
          </Col>


          <hr />


        </div>
      </main>
    </div>
  );
}
