import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles1/Home.module.css";
import { Col, DatePicker, Form, Input, Radio, Row, Select, Card, Button, Modal } from "antd";
import { useDispatch, useSelector } from "react-redux";
import { useState, useEffect } from "react";

export default function Home() {
  const [isModalVisible, setIsModalVisible] = useState(false);

  const showModal = () => {
    setIsModalVisible(true);
  };

  const handleOk = () => {
    setIsModalVisible(false);
  };

  const handleCancel = () => {
    setIsModalVisible(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Modal Example
        </p>

        <div className={styles.grid}>
          <Col md={30} xs={30} style={{ marginRight: '20px' }}>
            <Form.Item
              label="Modal Example"
              name="modal_example_1"
            >
              <Button
                type="success"
                onClick={showModal}
                // loading={loadingSubmit || loading}
                // disabled={submitButton}
              >
                Show Modal
              </Button>
            </Form.Item>
          </Col>
        </div>
      </main>

      <Modal title="Modal Example" visible={isModalVisible} onOk={handleOk} onCancel={handleCancel}>
        <p>Modal Content</p>
      </Modal>
    </div>
  );
}
