import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles1/Home.module.css";
import { Col, DatePicker, Form, Input, Radio, Row, Select } from "antd";
import { useDispatch, useSelector } from "react-redux";
import { useState, useEffect } from "react";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to The <a href="https://nextjs.org">Jungle!</a>
        </h1> */}

        <p className={styles.description}>
          Radio Button Example
        </p>

        <div className={styles.grid}>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Radio Button 1"
						name="radio_example_1"
					>
					<Radio.Group
								>
								<Radio
										value={'YA'}
								>
										<span>
											Ya
										</span>
								</Radio>
								<Radio
										value={'TIDAK'}
									>
										<span>
											Tidak
										</span>
								</Radio>
							</Radio.Group>			
          </Form.Item>
				</Col>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Radio Button 2"
						name="radio_example_2"
					>
					<Radio.Group
								>
								<Radio
										value={'YA'}
								>
										<span>
											Ya
										</span>
								</Radio>
								<Radio
										value={'TIDAK'}
									>
										<span>
											Tidak
										</span>
								</Radio>
							</Radio.Group>
					</Form.Item>
				</Col>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Radio Button 3"
						name="radio_example_3"
					>
					<Radio.Group
          disabled
          defaultValue={'YA'}
								>
								<Radio
										value={'YA'}
								>
										<span>
											Ya
										</span>
								</Radio>
								<Radio
										value={'TIDAK'}
									>
										<span>
											Tidak
										</span>
								</Radio>
							</Radio.Group>
					</Form.Item>
				</Col>
				<Col md={30} xs={30} style={{marginRight: '20px'}}>
					<Form.Item
						label="Radio Button 4"
						name="radio_example_4"
					>
					<Radio.Group
          disabled
          defaultValue={'TIDAK'}
								>
								<Radio
										value={'YA'}
								>
										<span>
											Yes
										</span>
								</Radio>
								<Radio
										value={'TIDAK'}
									>
										<span>
											No
										</span>
								</Radio>
							</Radio.Group>
					</Form.Item>
				</Col>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}